<?php

namespace EvaluationBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * absenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class absenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAbsence($id)
    {
        try {
            return $this->createQueryBuilder('l')
                ->select('COUNT(l)')
                ->where('l.student = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }
    public function findAb($id)
    {
        try {
            return $this->createQueryBuilder('l')
                ->select('SUM( l.heureFin - l.heureDeb)')
                ->where('l.student = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }
    public function findSum()
    {
        try {
            return $this->createQueryBuilder('l')
                ->select('SUM( l.heureFin - l.heureDeb)')
                ->getQuery()
                ->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }

    }

