<?php

namespace EvaluationBundle\Repository;

/**
 * matiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matiereRepository extends \Doctrine\ORM\EntityRepository
{
}
