<?php

namespace EvaluationBundle\Repository;

/**
 * noteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class noteRepository extends \Doctrine\ORM\EntityRepository
{
    public function bestNote()
    {
        return $this->getEntityManager()->createQuery('SELECT note n from EvaluationBundle:note where n.noteexamen > 15')->getResult();
    }
}
