<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByName($searchName){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u
                FROM AppBundle:User u
                WHERE u.firstName LIKE :searchName '
            )
            ->setParameter('searchName', '%'.$searchName.'%')
            ->getResult();
    }

    public function findAdmin(){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT u
    FROM AppBundle:User u Where u.userType= 'Administrator' "
            )
            ->getResult();
    }
    public function findUsers()
    {
        return $this->getEntityManager()->createQuery("SELECT u FROM AppBundle:User where u.userType = 'NULL'")->getResult();
    }

    public function countParent()
    {
        try {
            return $this->createQueryBuilder('p')
                ->select('COUNT(p)')
                ->where('p.userType = :parent')->andwhere('p.enabled = :enabled')
                ->setParameter('parent', 'Parent')->setParameter('enabled',1)
                ->getQuery()
                ->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }


}
