materiel_homepage:
    path:     /
    defaults: { _controller: EvaluationBundle:Default:index }
template_aff:
    path:     /showb
    defaults: { _controller: EvaluationBundle:Evaluation:Template}
templatefront_aff:
    path:     /show
    defaults: { _controller: EvaluationBundle:Evaluation:TemplateF}
admin_AddClasse:
    path:     /AddClasse
    defaults: { _controller: EvaluationBundle:Classe:AddClasse }
admin_DeleteClasse:
    path:     /DeleteClasse/{id}
    defaults: { _controller: EvaluationBundle:Classe:DeleteClasse }
matiere_index:
    path:     /
    defaults: { _controller: EvaluationBundle:Matiere:index }
matiere_show:
    path:     /{id}/show
    defaults: { _controller: EvaluationBundle:Matiere:show }
admin_AddSubject:
    path:     /AddSubject
    defaults: { _controller: EvaluationBundle:Matiere:AddSubject }
admin_searchSubject:
    path:     /searchSubject
    defaults: { _controller: EvaluationBundle:Matiere:searchSubject }
admin_DeleteSubject:
    path:     /DeleteSubject/{id}
    defaults: { _controller: EvaluationBundle:Matiere:DeleteSubject }
admin_UpdateSubject:
    path:     /UpdateSubject/{id}
    defaults: { _controller: EvaluationBundle:Matiere:UpdateSubject }
AffectMark:
    path:     /AffectMark
    defaults: { _controller: EvaluationBundle:Note:AffectMark }
etudaint_markview :
    path:     /marksview
    defaults: { _controller: EvaluationBundle:Note:marksView}
etudaint_getmyforum :
    path:     /mysubjects
    defaults: { _controller: EtudiantBundle:Matiere:getmyForumSub}
ajout_front:
    path:     /ajoutfront
    defaults: { _controller: EvaluationBundle:Note:AjoutFront }
inscription_parent:
    path:     /inscri
    defaults: { _controller: EvaluationBundle:Note:AjoutParent }
afficher_parent:
    path:     /afficher
    defaults: { _controller: EvaluationBundle:Note:AfficherParent }
ajax_parent:
    path:     /ajax
    defaults: { _controller: EvaluationBundle:Note:search }
accepter_parent:
    path:     /accepter/{id}
    defaults: { _controller: EvaluationBundle:Note:AccepterParent }

refuser_parent:
    path:     /refuser/{id}
    defaults: { _controller: EvaluationBundle:Note:RefuserParent }
detail_parent:
    path:     /detail/{id}
    defaults: { _controller: EvaluationBundle:Note:DetailParent }
PDF:
    path:     /pdf/{id}
    defaults: { _controller: EvaluationBundle:Note:DisplayPDF }
addAbs:
    path:     /addAbs/{id}
    defaults: { _controller: EvaluationBundle:Absent:AddAbs }
etudiant_list:
    path:     /listeStudents
    defaults: { _controller: EvaluationBundle:Absent:allstudents }
addTeacher:
    path:     /addTeacher
    defaults: { _controller: EvaluationBundle:Absent:AddTeacher }
showTeacher:
    path:     /showTeacher
    defaults: { _controller: EvaluationBundle:Absent:ShowTeacher }
updateLogin:
    path:     /updateLogin/{id}
    defaults: { _controller: EvaluationBundle:Absent:UpdateLogin }
interfaceTeacher:
    path:     /interfaceTeacher/{id}
    defaults: { _controller: EvaluationBundle:Absent:Interface }
showAbsence:
    path:     /showAbsence/{id}
    defaults: { _controller: EvaluationBundle:Absent:ShowAbsence }
showStudentDetails:
    path:     /showStudentDetails/{id}
    defaults: { _controller: EvaluationBundle:Absent:ShowStudentDetails }



