materiel_homepage:
    path:     /
    defaults: { _controller: EvaluationBundle:Default:index }
template_aff:
    path:     /template
    defaults: { _controller: EvaluationBundle:Evaluation:Template}
templatefront_aff:
    path:     /templatefront
    defaults: { _controller: EvaluationBundle:Evaluation:TemplateF}

