materiel_homepage:
    path:     /
    defaults: { _controller: EvaluationBundle:Default:index }
template_aff:
    path:     /showb
    defaults: { _controller: EvaluationBundle:Evaluation:Template}
templatefront_aff:
    path:     /show
    defaults: { _controller: EvaluationBundle:Evaluation:TemplateF}


